---
title: "W4 practice"
output:
  pdf_document: default
  html_document: default
date: '2023-02-01'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 4, fig.height = 3, fig.align = "center", warning = FALSE)


library(haven); library(psych); library(dplyr); 
library(magrittr); library(ggplot2); library(gridExtra)
# library(epitools); library(lsr); library(descr); library(epiR); library(epiDisplay)

```


# 0. data step 
```{r}


 dat = data.frame(Patient = c(1:10), 
            SBP = c(110, 124, 116, 120, 135, 148, 136, 165, 152, 172),
            DBP = c( 65, 70, 75, 80, 85, 90, 95,100,105,110))

```  

# 1. Scatterplot  

```{r}
  tmp.plot = 
  dat %>% ggplot(aes(x = DBP, y = SBP)) + 
  geom_point() + 
  xlab("Diastolic blood pressure") + # x-axis label
  ylab("Systolic blood pressure") + # y-axis label
  labs(title = "Plotting SBP vs. DBP", caption = "simple scatter plot") + 
  theme_bw()
  
  
```

# 2. adding regression line

```{r}

  tmp.plot + # adding to the plot above
  geom_smooth(method='lm', formula= y ~ x) + # regression line 
  geom_hline(yintercept = mean(dat$SBP)) # mean line 


```


# 3. linear regression

```{r}

  fit = lm(SBP ~ DBP, data = dat) # fitting a regression model
  summary(fit)  
  plot(fit) # diagnostic plots 
  
  library(jtools) # summary tool
  summ(fit) 
  summ(fit, scale = TRUE) # gives standardized coefficients
  summ(fit, confint = TRUE, digits = 3) # with confidence intervals
  plot_summs(fit) # coefficient plot
  export_summs(fit) # table
  
```

# 4. ANOVA paw lift 
```{r}

  rat = data.frame(rat_id = c(1:72), 
                 drug = factor(c(rep(c("A", "B", "C"), each = 8, times = 3))),
                 timelift = c(5.2, 5.1, 2.4, 4.3, 3.1, 2.4, 4.2, 5.0, 2.4, 2.4, 4.6, 1.2, 5.1, 5.2, 2.9,  3.3, 4.5, 3.2, 4.6, 5.0, 2.8, 2.9, 4.1, 2.2, 3.8, 4.1, 2.4, 3.9, 3.8, 2.2, 4.7, 4.5, 2.6, 3.9, 3.1, 3.4, 3.4, 4.5, 3.6, 3.9, 4.2, 2.0, 4.3, 3.5, 2.6, 2.8, 2.9, 3.1, 5.0, 4.0, 1.8, 3.5, 3.8, 2.9, 2.1, 3.1, 2.9, 4.2, 3.7, 3.4, 3.7, 3.9, 3.7, 3.6, 3.9, 2.6, 3.2, 3.2, 2.8, 2.9, 5.1, 3.1))

  describe(rat)
  describeBy(rat, "drug") # descriptive stats by drug
  rat %>% filter(drug == "A") %>% describe 
  
  rat["drug" = "A",]
  
  fit2 = lm(timelift ~ drug, data = rat) # regression
  summary(fit2)
  
  rat$drug = relevel(rat$drug, ref = c("B"))
  
  library(multcomp) 
  tmp.comp = glht(fit2, linfct = mcp(drug = "Tukey")) # multiple comparison with Tukey method
  summary(tmp.comp)  
  plot(tmp.comp)
  
  rat %>% 
    ggplot(aes(x=drug, y=timelift)) + # create a boxplot
    geom_boxplot() + 
    stat_summary(fun.y = "mean") + # draw mean
    theme_bw()


```

# 5. Create indicator variables  
```{r}

  ratsreg = 
  rat %>% mutate(drugA = ifelse(drug == "A", 1, 0),
                 drugB = ifelse(drug == "B", 1, 0),
                 drugC = ifelse(drug == "C", 1, 0))
  
  table(ratsreg$drug, ratsreg$drugA)
  table(ratsreg$drug, ratsreg$drugB)
  
  fit3 = lm(timelift ~ drugA + drugB, data = ratsreg)
  summary(fit3)
``` 

# 6. Example 3. Gentamicin
```{r}

 lect4a = data.frame(id = c(1:12),
                     hgb = c(9.7 ,10.9,11.3,12.0,13.5,13.7,14.2,13.2,12.5,11.7,10.5,11.2),
                     hct = c(29.4,32.7,33.1,36.1,40.9,41.3,42.0,40.0,38.2,35.2,31.0,34.8),
                     concn = c(9.5,8.7,7.2,7.7,5.8,5.9,5.6,5.5,6.6,7.0,8.1,7.9))
 
 lect4a %>% describe
 
 lect4a %>% 
   ggplot(aes(x=hct, y=concn, label=id)) + 
   geom_point() +
   geom_text(hjust=0, vjust=0) + 
   xlab("Hematrocrit") + 
   ylab("Hematrocrit") + 
   labs(title = "Plotting concentration by hct") +
   theme_bw()

```

# 7. correlation
```{r}

  corr.test(lect4a[,c('hct', 'concn')]) # coefficient and p-values
  pairs.panels(lect4a[,c('hct', 'concn')]) # more visuals
  lowerCor(lect4a[,c('hct', 'concn')]) # lower correlation plot 
  
  fit4 = lm(concn ~ hct, data = lect4a)
  summary(fit4)
  
  anova(fit4) #anova
  
  lect4a %>% ggplot(aes(x=hct, y=concn)) + 
    geom_point() +
    geom_smooth(method='lm', formula= y~x) + 
    theme_bw()
  
```

