---
title: "exrcise 2"
output:
  pdf_document: default
  html_document: default
date: '2023-03-29'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 4, fig.height = 3, fig.align = "center", warning = FALSE, message = FALSE)


##########################################
################ exercise 2 ##############
##########################################

```


# Q1

```{r}

  library(haven); library(psych); library(dplyr); 
  library(magrittr); library(ggplot2); library(gridExtra)
  library(rstatix); library(multcomp); library(ggeffects)

# Read the data

  extwo = read.csv("Ex2_data.csv")

# Data manipulation
  extwo = 
    extwo %>%
    mutate(hasevpsta = ifelse(hasevpst == 99, NA, hasevpst),
           hafrqpsta = ifelse(hafrqpst == 99, NA, hafrqpst),
           mispst = ifelse(hasevpst == 99 | hafrqpst == 99, 1, 0))
  
 # Convert all 99s to NAs  
  extwo =
    extwo %>%
    mutate_all(~replace(., . == 99, NA)) 


# Frequency tables
  xtabs(~ mispst + male, data = extwo)
  xtabs(~ mispst + newrx, data = extwo)
  xtabs(~ mispst + topir, data = extwo)
  xtabs(~ mispst + raceth, data = extwo)
  xtabs(~ mispst + hasevpre, data = extwo)

# Means by group
  extwo %>%
    group_by(mispst) %>%
    summarise(age.mean = mean(age, na.rm = TRUE),
              hafrqpre.mean = mean(hafrqpre, na.rm = TRUE),
              hit6pre.mean = mean(hit6pre, na.rm = TRUE))
  
  
```

# Q2

```{r}
  library(tableone)
  
  CreateTableOne(vars = c("hafrqpre", "hasevpre", "hit6pre", 
                          "raceth", "male", "age", "topir"), 
                 strata = c("newrx"), data = extwo,
                            factorVars = c("raceth", "male", "topir"))

  cat("or alternatively...")  
  
  bothdrugs =
    extwo %>%
    mutate(both = 
             case_when(newrx == 1 & topir == 1 ~ 3,
                       newrx == 0 & topir == 1 ~ 2,
                       newrx == 1 & topir == 0 ~ 1, TRUE ~ 0),
           sevpre = 
             case_when(hasevpre %in% 8:10 ~ 1, 
                       hasevpre < 8 ~ 0))
  
  CreateTableOne(vars = c("hafrqpre", "hasevpre", "hit6pre", 
                          "raceth", "male", "age", "topir"), 
                 strata = c("both"), data = bothdrugs,
                            factorVars = c("raceth", "male", "topir"))

  
```

# Q3

```{r}

  corr.test(extwo %>% dplyr::select("hit6pre", "hit6pst"))

```

# Q4

```{r}

 # Paired t-test for new drug group
  t.test(Pair(hafrqpre, hafrqpst) ~ 1, data = extwo %>% 
           filter(newrx == 1)) 
 
 # Between group t-test
  t.test(hafrqpre ~ newrx, data = extwo)

 # Descriptive stats by group
  CreateContTable(vars = c("hafrqpre", "hafrqpst"), 
                  strata = "newrx", data = extwo)
  
  
```

# Q5

```{r}

 # Between group t-test
  t.test(hit6pst ~ newrx, data = extwo)

 # LM
  fit = lm(hit6pst ~ newrx, data = extwo)
  confint(fit)  
  
```

# Q6

```{r}
  
 # Fit lm model with a interaction term
  fit = lm(I(hit6pst - hit6pre) ~ topir * newrx, data = extwo)
  summary(fit)  
  confint(fit) # confidence interaval 
  
 # This works too!   
  library(apaTables)
  apa.reg.table(fit)
```

# Q7

```{r}
  
 # Fit ANCOVA model
  fit = lm(hit6pst ~ hit6pre + topir + newrx, data = extwo)
  summary(fit)  
  confint(fit) # confidence interaval 
  
 # Calculate adjusted means   
  library(emmeans)
  lsmeans = 
    emmeans(fit, ~ factor(newrx))

```

