---
title: "W5 practice"
output:
  pdf_document: default
  html_document: default
date: '2023-02-09'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


##########################################
############# week 3 exercise ############
##########################################
library(haven); library(psych); library(dplyr); 
library(magrittr); library(ggplot2); library(gridExtra)
library(epitools); library(lsr); library(descr); library(epiR); library(epiDisplay)

```


# 0. data step 
```{r}

library(haven); library(psych); library(dplyr); 
library(magrittr); library(ggplot2); library(gridExtra)
library(epitools); library(lsr); library(descr); library(epiR); library(epiDisplay)

  dat = read_sas("SASlab/Choices.sas7bdat") # load data 
  names(dat) # name of the variables
  dat %>% dim # 2536, 16
  summary(dat) # get min, max, NA's
  describe(dat)
```  

# 1. Create a new variables 

```{r}
  center = 
    dat %>% 
    mutate(agecnt = age - mean(dat$age, na.rm = TRUE), # na.rm - ignore NAs when calculate
           agemin = age - min(dat$age, na.rm =TRUE),
           nhb = ifelse(race == 2, 1, 0),
           race = factor(race, levels = c("1", "2"), labels = c("NHW", "NHB")))

```

# 2. Regression and partial correlation

```{r}

# first model
 fit1 = lm(qwb100 ~ nhb + agemin, data = center)
 summary(fit1)
 
 coef(fit1) # call coefficients
 confint(fit1) # CIs
 fit1 %>% names

# second model  
 fit2 = lm(qwb100 ~ religion + race + age + depress + married + health, data = center)
 summary(fit2)
 
 tmp.r = 
   center[,c('religion', 'race', 'age', 'depress', 'married', 'health', 'qwb100')] %>% 
   lowerCor() # use corr matrix for partial.r function
 
 psych::partial.r(tmp.r, x = 4:6, y = 1:3) # 
 # partial correlation, y = col numbers of things we would like to control for
 
```


# 3. MULTICOLLINEARITY

```{r}

 library(car)
 vif(fit2) # EVALUATE MULTICOLLINEARITY
 
 tmp.r # check correlations
       # or compare unadjusted coef with adjusted ones 

```

# 4. WHAT IF WE USE A CLASS STATMENT TO CREATE AN INDICATOR VARIABLE FOR RACE
```{r}
 three = 
  center %>% 
  mutate(male = ifelse(gender == 2, 1, 0))

 table(three$male, three$gender)
 table(three$nhb, three$race)
 
 fit3 = lm(qwb100 ~ agemin + depress + male + nhb + married, data = three %>% na.omit())
 summary(fit3)
 
```

# 5. Partial F test  
```{r}

 fit4 = lm(qwb100 ~ age + depress + nhb, data = three %>% na.omit())
 anova(fit3, fit4) # partial F test

``` 

